### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by tibr** [rheinfabrik/Heimdall.droid#27]
I think that we should add CircleCI.

**Comment by Gi-lo** [comment]
We had massive problems using CircleCI for our Android builds. I suggest using Travis instead. What do you think @AHarazim ?

**Comment by tibr** [comment]
I think that we should try CircleCI first before using Travis as a last resort. We could use our paid CircleCI plan so that the CI is super fast.

**Comment by AHarazim** [comment]
We can give CircleCI a try. When I finish my work, I will try it. I think at the end of the week.

**Comment by Gi-lo** [comment]
:+1:
