### ISSUE TITLE
Question: minSDK

### ISSUE THREAD

**Issue by eyedol** [rheinfabrik/Heimdall.droid#31]
Any reason why this library's minSDK is so high? Currently is at `15`

**Comment by eyedol** [comment]
My suspicion is because of `android-spock`. Right? In version [`1.2.1`](https://github.com/pieces029/android-spock/blob/master/CHANGELOG.md) they have added support for minSDK 8

**Comment by Gi-lo** [comment]
@eyedo If I recap correctly, Spock was the sole reason for the minSDK version of 15.  I'll review your corresponding PR (https://github.com/rheinfabrik/Heimdall.droid/pull/32) tomorrow in the morning to check if something does not work as expected.

 Thanks for you anticipation.

**Comment by Gi-lo** [comment]
See: https://github.com/rheinfabrik/Heimdall.droid/releases/tag/1.0.3

**Comment by eyedol** [comment]
Awesome! Thanks for publishing a release immediately.

**Comment by Gi-lo** [comment]
You're welome :)
