### ISSUE TITLE
Do you have any plans for a future development?

### ISSUE THREAD

**Issue by Rainer-Lang** [rheinfabrik/Heimdall.droid#34]

**Comment by Gi-lo** [comment]
What do you have in mind? 

If there is anything that you find missing, please open up an issue and we can discuss it there. Same for bugs.

**Comment by Rainer-Lang** [comment]
Just wanted to know if rheinfabrik has something in pipeline and all could be improved... ;-)

I'm using Heimdall and it's really great. Heimdall solved a really hard problem for me. Thanks to Rheinfabrik.

**Comment by Gi-lo** [comment]
Thanks for your kind words. Again, if you have any feature requests or improvement ideas feel free to create issues :)
