### ISSUE TITLE
Upgrade to rxandroid 1.x and rxlilfecycle

### ISSUE THREAD

**Issue by Rainer-Lang** [rheinfabrik/Heimdall.droid#36]

**Comment by Gi-lo** [comment]
I guess you mean the sample application. Correct?

**Comment by Rainer-Lang** [comment]
Yes and if necessary also the lib.

**Comment by Gi-lo** [comment]
The lib is based on RxJava not Android. But let's update it to the latest version as well :)

**Comment by Rainer-Lang** [comment]
Thanks.

**Comment by Rainer-Lang** [comment]
@Gi-lo Maybe ```RxAppCompatActivity_Heimdall``` could be replaced by ```com.trello.rxlifecycle.components.support.RxAppCompatActivity```.

**Comment by Gi-lo** [comment]
Yes, generally it is  a good idea to update the state of the example application to use more modern technology. I hope I can find some time to update it beginning next week.

**Comment by Rainer-Lang** [comment]
Would be really great.

**Comment by Gi-lo** [comment]
@Rainer-Lang Please take a look at https://github.com/rheinfabrik/Heimdall.droid/pull/37 and provide feedback :)

**Comment by Rainer-Lang** [comment]
@Gi-lo Seems fine. Thanks.

**Comment by Gi-lo** [comment]
See: https://github.com/rheinfabrik/Heimdall.droid/releases/tag/1.0.4 :)

**Comment by Rainer-Lang** [comment]
@Gi-lo Thanks a lot. :-)
